### ISSUE TITLE
ホーム画面の作成

### ISSUE THREAD

**Issue by NJK-Labo** [NJK-Labo/mailfilter#1]
ホーム画面（ルート）を作成する

- [x] 初期設定を行う（環境ごとの読み込み設定など）
- [x] 問い合わせメール一覧画面（/contact-emails）へのリンクを作成する
- [x] 求人関係メール一覧画面（/job-emails）へのリンクを作成する
- [x] エラーページ（404、500）を作成する
- [x] テストを作成する

**Comment by kataNjk** [comment]
マージされたのでクローズします。
