### ISSUE TITLE
一覧画面の作成

### ISSUE THREAD

**Issue by NJK-Labo** [NJK-Labo/mailfilter#2]
問い合わせ一覧と求人関係一覧の画面を作成する
~~これらの画面に表示するメールのデータは、~~
~~当システムの外から直接テーブルに入ってくるものとする。~~
~~（MicrosoftPowerAutomateを用いて直接テーブルにInsertする）~~

~~※今後の修正で、当システムからCSVインポートなどで~~
　~~メールを取り込むという修正がされるかもしれないが、~~
　~~現在のところはテーブルのデータは自動的に入るものとする~~

**データはCSVインポート機能でインポートされるものとする**

- [x] モデルを作成する
- [x] マイグレーションファイルを作成する
- [x] 問い合わせ一覧画面を作成する
- [x] 求人関係一覧画面を作成する
- [x] テストを作成する

**Comment by kataNjk** [comment]
テストについては残課題があるため、オープンのままにしておきます。

**Comment by kataNjk** [comment]
テストがうまく動作しない問題については、プロジェクト全体についての問題のため、別途イシューを作って対応することにします。
このイシューはクローズします。
