### ISSUE TITLE
詳細画面の作成

### ISSUE THREAD

**Issue by NJK-Labo** [NJK-Labo/mailfilter#8]
一覧画面の詳細ボタンを押下すると、そのデータの詳細画面に遷移する。

- [x] 問い合わせメール詳細画面を作成し、問い合わせメール一覧画面から詳細画面に遷移できるようにする
- [x] 求人関係メール詳細画面を作成し、求人関係メール一覧画面から詳細画面に遷移できるようにする
~~- [ ] 詳細画面で「一覧に戻る」リンクを押下したときに、検索条件が遷移前の状態に戻っている~~
~~- [ ] 詳細画面で「一覧に戻る」リンクを押下したときに、ページ数が遷移前の状態に戻っている~~
~~- [ ] 詳細画面で「一覧に戻る」リンクを押下したときに、並び順が遷移前の状態に戻っている~~
- [x] テストを作成する

**Comment by kataNjk** [comment]
・詳細画面で「一覧に戻る」リンクを押下したときに、検索条件が遷移前の状態に戻っている
　については、検索機能のISSUEで確認します。ref. #3 

詳細画面で「一覧に戻る」リンクを押下したときに、ページ数が遷移前の状態に戻っている
　については、ページ送り機能のISSUEで確認します。 ref, #4 

詳細画面で「一覧に戻る」リンクを押下したときに、並び順が遷移前の状態に戻っている
　については、並び替え機能のISSUEで確認します。 ref. #5

**Comment by kataNjk** [comment]
#15 でマージされたのでクローズします。
